### ISSUE TITLE
TWTRComposer height problem

### ISSUE THREAD

**Issue by OhadMaor-VIA** [twitter/twitter-kit-ios#37] opened 2018-03-06 13:53 UTC
**Bug Report**
I don't understand why you have closed the [same bug](https://github.com/twitter/twitter-kit-ios/issues/1) that is still exist.

* Steps to reproduce the problem:
When setting a TWTRComposer using the [snip code](https://github.com/twitter/twitter-kit-ios/wiki/Compose-Tweets) with predefined text, the height of the Tweet view doesn't update:
<img width="175" alt="screen shot 2018-03-06 at 15 47 52" src="https://user-images.githubusercontent.com/34231750/37035911-b394c914-2156-11e8-81dc-e2e762f0dd23.png">

* Expected behavior:
Tweet should have a height that let's the user scroll and look at the pre-defined text tweet.
_Example:_
Tap on the opened tweet with the predefined text, and tap any character inside the Tweet view, the height grows up immediately.

- [ ]  iOS Version (iOS 11.2):
- [ ]  iOS Device Model (iPhone 5S all the way up to X):
- [ ]  TwitterKit version 3.3.0

**Comment by JoshRonk** [comment] 2018-03-12 22:11
Same issue here been holding off on an app update waiting on this fix. Any idea when this update will be released.

**Comment by npu3pak** [comment] 2018-03-16 10:10
Same issue

**Comment by OhadMaor-VIA** [comment] 2018-03-26 06:42
@npu3pak TWTRComposer has no view property. Which type did you use to present a composer ?

**Comment by JacobJT** [comment] 2018-03-27 17:04
Not only does the height not fit the text, but you're unable to scroll.

This is only until the text is modified by the user.  One any text is modified, the view adjusts its height to fix the text.

**Comment by npu3pak** [comment] 2018-03-28 11:56
@OhadMaor-VIA Oh, totally forgot to mention it. I used TWTRComposerViewController.

**Comment by OhadMaor-VIA** [comment] 2018-03-28 12:16
@npu3pak , I've tried that also and it doesn't work. 
Which TwitterKit version do you have ?

**Comment by npu3pak** [comment] 2018-03-30 04:19
@OhadMaor-VIA 
`
pod 'TwitterCore', '3.1.0'
pod 'TwitterKit', '3.3.0'
`
Try other constraints search criteria. Try to print constraints and find suspicious one. Then try to find constraint by height, for example. If I remember correctly, it is 48.

**Comment by LyndseyScott** [comment] 2018-04-01 01:06
@OhadMaor-VIA That workaround works for me. Thanks!

**Comment by OhadMaor-VIA** [comment] 2018-04-01 06:41
@LyndseyScott Can you please share the editing combined with @npu3pak workaround ? Thanks.

**Comment by ashusath** [comment] 2018-04-19 11:52
any update on this issue?

**Comment by wollars** [comment] 2018-05-15 15:47
I was able to use the code from @npu3pak without modification to get this working. All you need to do is present TWTRComposerViewController first and grab the scrollView in the completion handler.

**Comment by batuhanaltun** [comment] 2018-05-31 09:19
still no update from twitter, funny

**Comment by JacobJT** [comment] 2018-05-31 16:18
@batuhanaltun They gave an update - they're abandoning the repo. There was a blog post like a month ago about it. They say to use a web view now or something.

**Comment by wolfcon** [comment] 2018-06-12 08:22
Why not updated yet...lol
Almost half a year....2 thousand years later...

**Comment by evansobkowicz** [comment] 2018-07-16 16:13
A [fix](https://github.com/twitter/twitter-kit-ios/pull/9) for this was merged and released in Twitter Kit 3.4.0. Please try the new version and see if that solves your issue.

**Closed by evansobkowicz** 2018-07-16 16:13 UTC

**Comment by matteinn** [comment] 2018-10-04 14:13
The issue is still there for me

**Comment by cocoalasca** [comment] 2018-12-15 16:27
This issue is should not be close this still happens with latest versions

**Comment by romanfurman6** [comment] 2019-02-14 23:37
Just a temporary solution, if you don't want to fork it
ComposerVC -> ViewDidLayoutSubviews (on second event)
```
guard
    let scrollView = findView(ofType: UIScrollView.self, in: composerVC.view),
    let scrollViewSuperView = scrollView.superview,
    let textView = findView(ofType: UITextView.self, in: composerVC.view),
    let heightConstraint = textView.constraints.first(where: { $0.firstAttribute == .height }),
    let oldConstraint = scrollView.constraintsAffectingLayout(for: .vertical).first(where: { $0.firstAttribute == .top && $0.secondAttribute == .top })
else { return }

oldConstraint.isActive = false
scrollView.topAnchor.constraint(equalTo: scrollViewSuperView.topAnchor).isActive = true
heightConstraint.constant = 150
composerVC.view.layoutIfNeeded()
```
